### ISSUE TITLE
Verificación de usuarios

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#415]
Debemos darle un repaso al flow de verificación y ver si todo cuadra.

- [x] Incentivar que la gente se verifique (#308)
- [ ] Me voy y continuo luego verificándome (#302)
- [x] Me he pasado de intentos de verificación (#279)
- [x] Redirigir al enviar la carta (#395)
- [x] Máximo número de intentos de verificación para cartas (#332)
- [x] Guardar peticiones fallidas al Padrón (#277) 
- [x] Seguimiento de cuantos usuarios se han verificado (#399)

**Comment by Poliuk** [comment]
No sé si lo tenéis contemplado, pero visto el alud de trolls que han inundado la web hoy, añadiría la verificación por SMS como una medida para evitar el registro masivo de cuentas falsas.

**Comment by xkill** [comment]
Pues con arreglar el CAPTCHA os quitais unos cuantos bots #407

**Comment by Poliuk** [comment]
@xkill no estoy tan seguro de que la gente quiera comprometer su teléfono (que está identificado contra un DNI) por trollear un rato, hay demasiadas webs más fáciles.

**Comment by jmorenoamor** [comment]
@xkill @Poliuk Ahí tienes razón, no va a quitar todos, pero solo por la "pereza" de ese paso, se ahorrarían unos cuantos trolls. De todas formas creo que en los próximos días habrá menos, lo de hoy es por la novedad, en una semana se habrán olvidado de ella y estarán con otra cosa.

**Comment by xkill** [comment]
@Poliuk: "no estoy tan seguro de que la gente[...]" , creo que el no estar seguro de las cosas da lugar a error. Yo te aseguro que el sistema CAPTCHA y de verificacion que hay ahora mismo se puede saltar automaticamente (working on it....)

**Comment by xuanxu** [comment]
Gracias por vuestras sugerencias, el tema del Captcha lo tenemos en mente para mejorarlo o cambiarlo por algo más accesible y que sea robusto, le estamos dando vueltas a estos temas, de todas formas un par de puntualizaciones:

-El registro no se va a complicar más. Aunque hemos visto por ahí que alguien se ha tomado como un "fallo de seguridad" que baste un email y un password en realidad es una feature: se intenta que la barrera de acceso a la participación sea la más baja posible. Sabemos que eso implica tratar con trolls, es algo que aceptamos y para lo que poco a poco mejoraremos las herramientas de moderación/administración (estamos en el día 1 de un proyecto desarrollado en un mes). Nada de lo que ha pasado con forocoches nos preocupa demasiado, los moderadores cada vez van a disponer de mejores herramientas y los algoritmos para filtrar los debates trol de la portada se irán tuneando.

-Este issue no tiene nada que ver con el tema de registro de usuarios, la validación a la que se refiere el título es un paso independiente y voluntario, es una validación contra el padrón para verificar usuarios madrileños que son los que tendrán capacidad de apoyar propuestas populares (lo que hay ahora en producción son debates, un simple foro de intercambio de opiniones en el que los concejales/responsables y ediles tienen usuario y pueden responder/participar).

**Comment by h3ku** [comment]
No se cuantas vueltan necesitais darle cuando es tan facil como poner recaptcha, que encima como extra la nueva version facilita aun mas el registro que es lo que buscais sin la posibilidades de uso de bots.

**Comment by xuanxu** [comment]
@h3ku entendemos tu cuestión, si ves el histórico del repo verás que nuestra primera versión usaba recaptcha, pero eso es un tema institucional de independencia tecnológica, siendo una web del ayuntamiento no podemos utilizar herramientas externas para ciertas cosas. En concreto si ponemos recaptch, Google tendría registro de cada vez que un madrileño participa e incluso podría potencialmente (aunque no lo hiciera) interrumpir el proceso de participación.
